# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f3c6af96481444882cd06b59193794391d34009ebcd8072a87d53a1bbaaaec6312c155c120a9edec774fc8423300bbc95d7aa6b63b1c279b428849eaf077bb7

test:
  secret_key_base: 7830614a823e74a5b0b1462f5de389ef350bf5963119db4f581c3a37b67088ae8b7996b60a731f9e3e3a3d9bef0ceb7f65612142af931b403f6b4c52cd51b11a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
